arch: null
artifacts: []
environment:
  BUILD_SUBMITTER: git.sr.ht
image: alpine/3.16
packages:
- rust
- cargo
- openssl-dev
- docker
repositories: {}
secrets:
- d8ac6870-95bb-4f51-8bc0-d70164136baa
- ba3c7daf-1c29-4099-aa0f-2d62633e648e
shell: false
sources:
- https://git.sr.ht/~estym/Drunk-Venti-Rust
tasks:
- setup : |
    sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
    sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
    sudo service cgroups start
    sudo service docker start
    cargo install cargo-get
    cat ~/nexus-secret | \
    sudo docker login r.evannregnault.dev --username sourcehut --password-stdin
- test: |
    cd Drunk-Venti-Rust
    cargo test
- build-image: |
    cd Drunk-Venti-Rust
    N=$(cargo get -n)
    sudo docker build -t r.evannregnault.dev/$N:latest ./
- push-image: |
    cd Drunk-Venti-Rust
    V=$(cargo get version --pretty)
    N=$(cargo get -n)
    sudo docker tag r.evannregnault.dev/$n:latest r.evannregnault.dev/$N:$V
    sudo docker push r.evannregnault.dev/$N:latest
    sudo docker push r.evannregnault.dev/$N:$V

triggers: []
oauth: ""
